# Generated by Django 4.2.16 on 2024-11-28 01:57

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mapping', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('zone', models.CharField(max_length=255)),
                ('capacity', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('manager', models.CharField(blank=True, max_length=255, null=True)),
                ('current_inventory', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('address_line1', models.CharField(blank=True, max_length=255, null=True, verbose_name='Alamat Baris 1')),
                ('address_line2', models.CharField(blank=True, max_length=255, null=True, verbose_name='Alamat Baris 2')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Alamat Email')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,15}$', "Phone number must be entered in the format: '+6281234567890'. Up to 15 digits allowed.")])),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mapping.kecamatan')),
                ('province', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mapping.provinsi')),
                ('regency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mapping.kabupatenkota')),
                ('village', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mapping.kelurahandesa')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
    ]
