# Generated by Django 4.2.16 on 2024-12-04 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_product_category_alter_product_product_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouseproduct',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='warehouseproduct',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='warehouseproduct',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='warehouseproduct',
            unique_together={('warehouse', 'product')},
        ),
    ]
