# Generated by Django 4.2.16 on 2024-12-04 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_warehouseproduct_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouseproduct',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='warehouseproduct',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
