# Generated by Django 5.1.3 on 2024-12-04 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_warehouseproduct_created_at_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='warehouseproduct',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='active',
        ),
    ]
